---
- name: Update-password
  hosts: 192.168.3.128
  tasks:
  - name: change-password 
    user:
     name: ansible-user
     password: "{{'ansible'| password_hash ('sha512')}}"
     update_password: always
     group: root
