---
- name: Desvription
  hosts: 192.168.3.128 
  
  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: present 
    tags: i-nginx

  - name: start the service
    service: 
      name: nginx
      state: started
      enabled: true
    tags: ss-nginx
